schema = 3

[mod]
  [mod."aidanwoods.dev/go-paseto"]
    version = "v1.5.2"
    hash = "sha256-nEVD1nZfNWNvoYGIUqOjGd/bgTrtzjiRi97/o6YZPeA="
  [mod."aidanwoods.dev/go-result"]
    version = "v0.1.0"
    hash = "sha256-An/dVTJbdHQCfIIWwupb0DURP7ucxC18hxqGnVJt2TA="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/coreos/go-oidc/v3"]
    version = "v3.11.0"
    hash = "sha256-iV7ff6YGPiorHFPxC6lnojYWszFjkgh86445eUvYywI="
  [mod."github.com/dgraph-io/badger/v4"]
    version = "v4.8.0"
    hash = "sha256-mcNMVsXpEhVrCt8vohl1jbz1oMHHSqWJ8lZzcavMXOY="
  [mod."github.com/dgraph-io/ristretto/v2"]
    version = "v2.2.0"
    hash = "sha256-FlyrD0i02l8Vh7DnS+R+t0En1IoMliEQIDvhGA+hXus="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/go-jose/go-jose/v4"]
    version = "v4.0.2"
    hash = "sha256-vwcozYxzPXkvCkR/rQOm6DJ5Yd+Muu9YC/2VzVUP50s="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.3"
    hash = "sha256-Nnp/dEVNMxLp3RSPDHZzGbI8BkSNuZMX0I0cjWKXXLA="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/golang-migrate/migrate/v4"]
    version = "v4.17.1"
    hash = "sha256-KT/7xzUXjvYD4ZwM6IK5RnjMC+d9GjoYu5ZEIn/n4K8="
  [mod."github.com/google/flatbuffers"]
    version = "v25.2.10+incompatible"
    hash = "sha256-qWFf58zxZzIdn+5dB9VRbhYPcZb39tCG/ePfC9dgn3M="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/hashicorp/errwrap"]
    version = "v1.1.0"
    hash = "sha256-6lwuMQOfBq+McrViN3maJTIeh4f8jbEqvLy2c9FvvFw="
  [mod."github.com/hashicorp/go-multierror"]
    version = "v1.1.1"
    hash = "sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA="
  [mod."github.com/jackc/pgerrcode"]
    version = "v0.0.0-20220416144525-469b46aa5efa"
    hash = "sha256-IaqDv1c+uj6U6cz/Y9cBOPPGOwEcPH2BjVJlYj/6AH4="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20240606120523-5a60cdf6a761"
    hash = "sha256-ETpGsLAA2wcm5xJBayr/mZrCE1YsWbnkbSSX3ptrFn0="
  [mod."github.com/jackc/pgx/v5"]
    version = "v5.7.5"
    hash = "sha256-+bzuXlJnsvNEGjuhHIiZwmWepEmwj3Fl1ktLD50IKlU="
  [mod."github.com/jackc/puddle/v2"]
    version = "v2.2.2"
    hash = "sha256-IUxdu4JYfsCh/qlz2SiUWu7EVPHhyooiVA4oaS2Z6yk="
  [mod."github.com/jmoiron/sqlx"]
    version = "v1.4.0"
    hash = "sha256-0H132+A983nBr2zEyCKsJoBCZlC9pG+ylEcGysxKL4M="
  [mod."github.com/klauspost/compress"]
    version = "v1.18.0"
    hash = "sha256-jc5pMU/HCBFOShMcngVwNMhz9wolxjOb579868LtOuk="
  [mod."github.com/lucasepe/codename"]
    version = "v0.2.0"
    hash = "sha256-iHWoBuOzJInakhqzkDTFT5xvuqqE4TRuwk2BCRmupbY="
  [mod."go.opentelemetry.io/auto/sdk"]
    version = "v1.1.0"
    hash = "sha256-cA9qCCu8P1NSJRxgmpfkfa5rKyn9X+Y/9FSmSd5xjyo="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.37.0"
    hash = "sha256-zWpyp9K8/Te86uhNjamchZctTdAnmHhoVw9m4ACfSoo="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.37.0"
    hash = "sha256-BWnkdldA3xzGhnaConzMAuQzOnugytIvrP6GjkZVAYg="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.37.0"
    hash = "sha256-FBeLOb5qmIiE9VmbgCf1l/xpndBqHkRiaPt1PvoKrVY="
  [mod."go.uber.org/atomic"]
    version = "v1.7.0"
    hash = "sha256-g83RSzO/5k8W3qyiIsrQbVq1F8qJGccdWEXTjkqUOfc="
  [mod."golang.org/x/crypto"]
    version = "v0.39.0"
    hash = "sha256-FtwjbVoAhZkx7F2hmzi9Y0J87CVVhWcrZzun+zWQLzc="
  [mod."golang.org/x/net"]
    version = "v0.41.0"
    hash = "sha256-6/pi8rNmGvBFzkJQXkXkMfL1Bjydhg3BgAMYDyQ/Uvg="
  [mod."golang.org/x/oauth2"]
    version = "v0.22.0"
    hash = "sha256-3gmmXfCcxYBMaXmKRzGBpX01h4lMenFPkqWT9TwqIBE="
  [mod."golang.org/x/sync"]
    version = "v0.15.0"
    hash = "sha256-Jf4ehm8H8YAWY6mM151RI5CbG7JcOFtmN0AZx4bE3UE="
  [mod."golang.org/x/sys"]
    version = "v0.34.0"
    hash = "sha256-5rZ7p8IaGli5X1sJbfIKOcOEwY4c0yQhinJPh2EtK50="
  [mod."golang.org/x/text"]
    version = "v0.26.0"
    hash = "sha256-N+27nBCyGvje0yCTlUzZoVZ0LRxx4AJ+eBlrFQVRlFQ="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.6"
    hash = "sha256-lT5qnefI5FDJnowz9PEkAGylH3+fE+A3DJDkAyy9RMc="
